name: build

on:
  push:
    branches: [ master, actions ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: [counter, html-hello-world, todo-mvc]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ${{ example }}/.spago
          ${{ example }}/output
          ${{ example }}/node_modules
        key: build-atrifacts-v1-${{ example }}-${{ hashFiles('${{ example }}/package-lock.json', '${{ example }}/spago.dhall', '${{ example }}/packages.dhall') }}
    - uses: actions/setup-node@v1
      with:
        node-version: 10.15
    - run: npm i
      working-directory: ./${{ example }}
    - run: npm run build
      working-directory: ./${{ example }}

